# Generated by Django 4.2.5 on 2023-09-05 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acessorio",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "acessório",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Cor",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "cores",
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
                ("nacionalidade", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="modelo", to="garagem.categoria"
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="modelo", to="garagem.marca"
                    ),
                ),
            ],
            options={
                "verbose_name": "modelo",
                "verbose_name_plural": "modelos",
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ano", models.IntegerField(default=0)),
                ("preco", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("descricao", models.CharField(max_length=100)),
                ("acessorios", models.ManyToManyField(related_name="acessorios", to="garagem.acessorio")),
                ("capa", models.ManyToManyField(related_name="+", to="uploader.image")),
                (
                    "cor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="veiculos", to="garagem.cor"
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="veiculos", to="garagem.modelo"
                    ),
                ),
            ],
            options={
                "verbose_name": "veículo",
            },
        ),
    ]
