# Generated by Django 4.1.7 on 2023-03-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nome',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descrição',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
