# Generated by Django 4.2 on 2023-08-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0006_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(related_name='veículos', to='garagem.acessorio'),
        ),
    ]
